title: "Origami Games"
description: "Origami Games is game development company that primarily makes Minecraft-related content, founded by Daniel Orr and Ian McFarlane in early 2019 to house their projects. Origami now has 10+ members and contributors, focusing on the Launch data pack and its SMP server for content creators!"

github: "origami-games"
discord: "6pXWfbw"
curseforge: "https://curseforge.com/minecraft/"
youtube: "channel/UCbnzwUs9_DC2a5w0iJTUuTw"
patreon: "origamigames"

# team social media
andante: "Andante"
andante-twitter: "Andantweets"
andante-github: "AndanteDevs"
andante-youtube: "channel/UC9NVFqVOj_hE6iAKxkf9kPg"

qbert: "Qbert"
qbert-twitter: "TheQbert"
qbert-github: "TinyAtomss"
qbert-youtube: "channel/UCSrZdKW3DaOfgr_qb-6M-Iw"
